import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { diffPinned } from "../lib/agreement/pin-check";
import { assertPinnable } from "../lib/agreement/present";
import type { PinnedAgreement } from "../lib/agreement/types";
import { askNodes } from "./agreement-nodes";

// Pin an AvServ agreement version into this build (docs/plans/31 §4):
//
//   pnpm agreement:pin v1
//
// Fetches GET /v1/agreement/<version> from the first node that answers,
// re-hashes the text, the assent line and every attestation against AvServ's
// published hashes, and only then writes lib/agreement/pinned.ts. Commit the
// result in its own PR; CI (`pnpm agreement:check`) re-verifies it.

async function main() {
  const version = process.argv[2];
  if (!version) {
    console.error("Usage: pnpm agreement:pin <version>");
    process.exit(2);
  }

  const answers = await askNodes(`/v1/agreement/${encodeURIComponent(version)}`);
  const answer = answers.find((a) => a.kind === "ok");
  if (!answer || answer.kind !== "ok") {
    console.error(`No node served ${version}:`, JSON.stringify(answers));
    process.exit(1);
  }
  const v = answer.body;

  const pin: PinnedAgreement = {
    version: v.version,
    text: v.text,
    assent: { text: v.assent.text },
    attestations: v.attestations.map((a) => ({ id: a.id, text: a.text, required: a.required })),
  };
  assertPinnable(pin.text);
  // The pin must reproduce every hash AvServ published, or the bytes changed in
  // transit (encoding, line endings) and an acceptance would be refused.
  const diffs = diffPinned(pin, v);
  if (diffs.length > 0) {
    console.error(`Refusing to pin ${version}: the fetched copy does not reproduce AvServ's hashes:`);
    for (const d of diffs) console.error(`  - ${d}`);
    process.exit(1);
  }

  const file = join(process.cwd(), "lib", "agreement", "pinned.ts");
  writeFileSync(
    file,
    `// GENERATED by scripts/pin-agreement.ts — do not edit by hand.
//
// The AvAI user agreement version this portal build presents (docs/plans/31
// §4), pinned from ${answer.node} (status "${v.status}", effective ${v.effectiveAt}).
// \`pnpm agreement:check\` (CI) re-verifies it against AvServ.

import type { PinnedAgreement } from "./types";

export const PINNED_AGREEMENT: PinnedAgreement | null = ${JSON.stringify(pin, null, 2)};
`,
  );
  console.log(`Pinned ${v.version} (${v.status}) from ${answer.node} → ${file}`);
}

main().catch((err) => {
  console.error("pin failed:", err);
  process.exit(1);
});
