// GENERATED by scripts/pin-agreement.ts — do not edit by hand.
//
// The AvAI user agreement version this portal build presents (docs/plans/31
// §4). null: AvServ has not published a version yet, so the agreement page
// offers no acceptance. To pin: `pnpm agreement:pin <version>`, which fetches
// the version from AvServ and verifies every hash before writing this file.
// `pnpm agreement:check` (CI) re-verifies it against AvServ.

import type { PinnedAgreement } from "./types";

export const PINNED_AGREEMENT: PinnedAgreement | null = null;
